# This is a copy of `Gtk::show_about_dialog`.

module Adw
  # This is a convenience function for showing an application’s about box. The constructed dialog is associated with
  # the parent window and NOT reused for future invocations of this function.
  def show_about_window(
    parent : Window?,
    *,
    application : Gtk::Application? = nil,
    application_icon : ::String? = nil,
    application_name : ::String? = nil,
    artists : Enumerable(::String)? = nil,
    can_focus : Bool? = nil,
    can_target : Bool? = nil,
    css_classes : Enumerable(::String)? = nil,
    css_name : ::String? = nil,
    child : Gtk::Widget? = nil,
    comments : ::String? = nil,
    content : Gtk::Widget? = nil,
    copyright : ::String? = nil,
    cursor : Gdk::Cursor? = nil,
    debug_info : ::String? = nil,
    debug_info_filename : ::String? = nil,
    decorated : Bool? = nil,
    default_height : Int32? = nil,
    default_widget : Gtk::Widget? = nil,
    default_width : Int32? = nil,
    deletable : Bool? = nil,
    designers : Enumerable(::String)? = nil,
    developer_name : ::String? = nil,
    developers : Enumerable(::String)? = nil,
    display : Gdk::Display? = nil,
    documenters : Enumerable(::String)? = nil,
    focus_on_click : Bool? = nil,
    focus_visible : Bool? = nil,
    focus_widget : Gtk::Widget? = nil,
    focusable : Bool? = nil,
    fullscreened : Bool? = nil,
    halign : Gtk::Align? = nil,
    handle_menubar_accel : Bool? = nil,
    has_default : Bool? = nil,
    has_focus : Bool? = nil,
    has_tooltip : Bool? = nil,
    height_request : Int32? = nil,
    hexpand : Bool? = nil,
    hexpand_set : Bool? = nil,
    hide_on_close : Bool? = nil,
    icon_name : ::String? = nil,
    is_active : Bool? = nil,
    issue_url : ::String? = nil,
    layout_manager : Gtk::LayoutManager? = nil,
    license : ::String? = nil,
    license_type : Gtk::License? = nil,
    margin_bottom : Int32? = nil,
    margin_end : Int32? = nil,
    margin_start : Int32? = nil,
    margin_top : Int32? = nil,
    maximized : Bool? = nil,
    mnemonics_visible : Bool? = nil,
    name : ::String? = nil,
    opacity : Float64? = nil,
    overflow : Gtk::Overflow? = nil,
    receives_default : Bool? = nil,
    release_notes : ::String? = nil,
    release_notes_version : ::String? = nil,
    resizable : Bool? = nil,
    root : Gtk::Root? = nil,
    scale_factor : Int32? = nil,
    sensitive : Bool? = nil,
    startup_id : ::String? = nil,
    support_url : ::String? = nil,
    title : ::String? = nil,
    tooltip_markup : ::String? = nil,
    tooltip_text : ::String? = nil,
    translator_credits : ::String? = nil,
    valign : Gtk::Align? = nil,
    version : ::String? = nil,
    vexpand : Bool? = nil,
    vexpand_set : Bool? = nil,
    visible : Bool? = nil,
    website : ::String? = nil,
    width_request : Int32? = nil
  )
    dialog = Adw::AboutWindow.new(
      application: application,
      application_icon: application_icon,
      application_name: application_name,
      artists: artists,
      can_focus: can_focus,
      can_target: can_target,
      css_classes: css_classes,
      css_name: css_name,
      child: child,
      comments: comments,
      content: content,
      copyright: copyright,
      cursor: cursor,
      debug_info: debug_info,
      debug_info_filename: debug_info_filename,
      decorated: decorated,
      default_height: default_height,
      default_widget: default_widget,
      default_width: default_width,
      deletable: deletable,
      destroy_with_parent: true,
      designers: designers,
      developer_name: developer_name,
      developers: developers,
      display: display,
      documenters: documenters,
      focus_on_click: focus_on_click,
      focus_visible: focus_visible,
      focus_widget: focus_widget,
      focusable: focusable,
      fullscreened: fullscreened,
      halign: halign,
      handle_menubar_accel: handle_menubar_accel,
      has_default: has_default,
      has_focus: has_focus,
      has_tooltip: has_tooltip,
      height_request: height_request,
      hexpand: hexpand,
      hexpand_set: hexpand_set,
      hide_on_close: hide_on_close,
      icon_name: icon_name,
      is_active: is_active,
      issue_url: issue_url,
      layout_manager: layout_manager,
      license: license,
      license_type: license_type,
      margin_bottom: margin_bottom,
      margin_end: margin_end,
      margin_start: margin_start,
      margin_top: margin_top,
      maximized: maximized,
      mnemonics_visible: mnemonics_visible,
      modal: true,
      name: name,
      opacity: opacity,
      overflow: overflow,
      receives_default: receives_default,
      release_notes: release_notes,
      release_notes_version: release_notes_version,
      resizable: resizable,
      root: root,
      scale_factor: scale_factor,
      sensitive: sensitive,
      startup_id: startup_id,
      support_url: support_url,
      title: title,
      tooltip_markup: tooltip_markup,
      tooltip_text: tooltip_text,
      transient_for: parent,
      translator_credits: translator_credits,
      valign: valign,
      version: version,
      vexpand: vexpand,
      vexpand_set: vexpand_set,
      visible: visible,
      website: website,
      width_request: width_request
    )
    dialog.close_request_signal.connect do
      dialog.destroy
      true
    end
    dialog.present
  end
end
