name: Specs & Lint

on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: fedora:35 # libadwaita, switch to :latest
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      - uses: crystal-lang/install-crystal@v1
      - name: Shards install
        run: shards install
      - name: Spec
        run: crystal spec || exit 1
      - name: Check formatting
        run: crystal tool format --check
