name: Docs

on:
  push:
    branches:
      - main
      - website
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/checkout@v2
        with:
          ref: website
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.17.2
          run_install: true
      - name: Build website
        run: |
          pnpm run build
          echo "libadwaita.geopjr.dev" > ./build/CNAME
      - name: Push to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: 1.1.1
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Build docs
        run: |
          crystal docs
      - name: Push to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: docs
