name: Stable Release

on: workflow_dispatch

jobs:
  stable:
    runs-on: ubuntu-latest
    container: ghcr.io/geopjr/crystal-gtk:latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: stable
      - name: Build bindings
        run: |
          rm -rf ./src/auto/
          shards install
          ./bin/gi-crystal -o ./src/auto/
      - name: Run specs
        run: crystal spec
      - name: Push to branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "chore: bump bindings"
            git push origin HEAD:stable
          fi
